apiVersion: v1
kind: Secret
metadata:
  name: sysdig-agent
  {{#if CLUSTER_SELECTOR}}
  annotations:
     configmanagement.gke.io/cluster-selector: {{ CLUSTER_SELECTOR }}
  {{/if}} 
data:
  access-key: {{ ACCESS_KEY }}