kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: newpolicy
spec:
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - ipBlock:
        cidr: 1.2.3.4
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: dev
    - ipBlock:
        cidr: 1.2.3.4
  