kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nsrole-app
  annotations:
      configmanagement.gke.io/cluster-selector: &quot;&quot;
      configmanagement.gke.io/namespace-selector: &quot;&quot;
rules:
- apiGroups: ["apps"]
  resources: ["deployment"]
  verbs: ["list","watch"]        
