steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--no-cache', '-t', 'gcr.io/$PROJECT_ID/anthos-app', '-f' , 'deploy/Dockerfile', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/anthos-app']

- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=deploy/deployment.yaml
  - --image=gcr.io/$PROJECT_ID/anthos-app
  - --location=us-central1-a
  - --cluster=gke-private
  - --namespace=anthosapp