apiVersion: v1
kind: Service
metadata:
  name: phlox
  labels:
    app: phlox
    service: phlox
spec:
  selector:
    app: phlox
  ports:
    - name: http
      port: 8080
      targetPort: 3000
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: phlox
  labels:
    name: phlox
    app: phlox
spec:
  replicas: 1
  revisionHistoryLimit: 10
  serviceName: "phlox"
  selector:
    matchLabels:
      name: phlox
      app: phlox
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: phlox
        app: phlox
    spec:
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 1000
      containers:
        - name: phlox
          image: "gcr.io/wipro-gcp-parsnet-poc/anthos-app"
          imagePullPolicy: Always
          resources:
            requests:
              memory: 1500Mi
              cpu: 1000m
            limits:
              memory: 1500Mi
              cpu: 1000m
          volumeMounts:
            - name: "appnewdata"
              mountPath: "/home/node/appnewdata"
          ports:
            - name: phlox
              containerPort: 3000
              protocol: TCP
          env:
            - name: BASE_PATH
              value: "/home/node/app"
            - name: DATA_PATH
              value: "/home/node/appnewdata"  
  volumeClaimTemplates:
  - metadata:
      name: "appnewdata'"
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
            storage: 10Gi

